Repository jlevy/og-equity-compensation, pull requests merged in 2018-07, with the labels that each got.

#103 Offers links hope
  README.md
Labels: links

#104 Intro edits and other structuring
  README.md
Labels: major

#130 Paywall emojis added
  README.md
Labels: formatting-only

#128 copyedits to Equity Comp Basics to vesting and cliffs
  README.md
Labels: copy-edits-only

#129 copyedits Tax Basics thru Taxes on EC
  README.md
Labels: copy-edits-only

#134 Changes to review on #129
  README.md
Labels: copy-edits-only

#131 copyedits, Evaluating EC thru end
  README.md
Labels: copy-edits-only

#133 Mild restructure (startups); BOD, captable; content review
  README.md
Labels: addition, restructure

#140 copy post restructure
  README.md
Labels: copy-edits-only

#142 equity comp small restructure
  README.md
Labels: improvement

#146 small copyedits
  README.md
Labels: copy-edits-only, improvement

#149 small language clarifications and deletions
  README.md
Labels: restructure, some-copy-edits

#156 Small copy and formatting
  README.md
Labels: copy-edits-only
