Repository jlevy/og-equity-compensation, pull requests merged in 2018-08, with the labels that each got.

#160 one more nit
  README.md
Labels: copy-edits-only

#166 Fixed the last smart quotes
  README.md
Labels: formatting-only

#169 Fix broken definition
  README.md
Labels: copy-edits-only

#171 fixed broken links
  README.md
Labels: formatting-only

#170 bolding for consistency
  README.md
Labels: formatting-only

#165 unbolded a few incidental terms
  README.md
Labels: formatting-only

#173 one more link
  README.md
Labels: formatting-only

#174 Prod edits
  README.md
Labels: prod-edits-only

#176 last abutting link instance corrected
  README.md
Labels: formatting-only

#179 Some copy edits
  README.md
Labels: copy-edits-only

#183 small change to definition
  README.md
Labels: improvement

#187 things to look for in the offer letter
  README.md
Labels: formatting-only

#185 Section rename (Plans and Scenarios)
  README.md
Labels: restructure

#190 AMT caps consistency
  README.md
Labels: formatting-only

#192 cap correction
  README.md
Labels: copy-edits-only

#198 edits for style and voice
  .DS_Store
  README.md
Labels: copy-edits-only
